<a href="https://colab.research.google.com/github/shyamalkar/Data_Science/blob/main/Casestudy_titanic_pandas_3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# ***`Titanic Ml Problem`***

``Problem``

So many people die in 1912 for Titannic disastar, Some information are write in dataset .

Age
Sex
Ticket Class
Fare
Cabin
Family members


Use this information we predict how many passenger are die and alive ?

``Problem:- ``
     Given passenger information such as age, sex, ticket class and fare,
build a machine learning model that predicts whether a passenger survived
the Titanic disaster or not.

#``Reading CSV``

Download the file from encounters.csv and transfer in my working directory.


🚨Importent :-

Make sure that if you use Kaggle dataset then at first install kaggle .

!pip install kaggle

In [ ]:
!pip install kaggle

Requirement already satisfied: kaggle in /usr/local/lib/python3.12/dist-packages (1.7.4.5)
Requirement already satisfied: bleach in /usr/local/lib/python3.12/dist-packages (from kaggle) (6.3.0)
Requirement already satisfied: certifi>=14.05.14 in /usr/local/lib/python3.12/dist-packages (from kaggle) (2026.2.25)
Requirement already satisfied: charset-normalizer in /usr/local/lib/python3.12/dist-packages (from kaggle) (3.4.4)
Requirement already satisfied: idna in /usr/local/lib/python3.12/dist-packages (from kaggle) (3.11)
Requirement already satisfied: protobuf in /usr/local/lib/python3.12/dist-packages (from kaggle) (5.29.6)
Requirement already satisfied: python-dateutil>=2.5.3 in /usr/local/lib/python3.12/dist-packages (from kaggle) (2.9.0.post0)
Requirement already satisfied: python-slugify in /usr/local/lib/python3.12/dist-packages (from kaggle) (8.0.4)
Requirement already satisfied: requests in /usr/local/lib/python3.12/dist-packages (from kaggle) (2.32.4)
Requirement already satisfied: setuptools>=21.0.0 in /usr/local/lib/python3.12/dist-packages (from kaggle) (75.2.0)
Requirement already satisfied: six>=1.10 in /usr/local/lib/python3.12/dist-packages (from kaggle) (1.17.0)
Requirement already satisfied: text-unidecode in /usr/local/lib/python3.12/dist-packages (from kaggle) (1.3)
Requirement already satisfied: tqdm in /usr/local/lib/python3.12/dist-packages (from kaggle) (4.67.3)
Requirement already satisfied: urllib3>=1.15.1 in /usr/local/lib/python3.12/dist-packages (from kaggle) (2.5.0)
Requirement already satisfied: webencodings in /usr/local/lib/python3.12/dist-packages (from kaggle) (0.5.1)

In [ ]:
from google.colab import files
files.upload()

Saving kaggle.json to kaggle.json

{'kaggle.json': b'{"username":"shyamalb2","key":"c595f670b6b0fde52b34befcea84944d"}'}

In [ ]:
!mkdir -p ~/.kaggle
#Meaning :- mkdir = Create folder
            # ~ = home directory
            #.kaggle -> kaggle configuration create
            # -p means -> If folder create already then not show error.

In [ ]:
!cp kaggle.json ~/.kaggle/ # cp -> copy command
                           #Kaggle - api key file
                           # ~/.kaggle/ - destination folder

In [ ]:
!chmod 600 ~/.kaggle/kaggle.json # chmod -> file permission change
# 600 means

In [ ]:
!kaggle datasets download -d emrullahdemirhan/titaniccsv #Owner/datasetname

Dataset URL: https://www.kaggle.com/datasets/emrullahdemirhan/titaniccsv
License(s): unknown
Downloading titaniccsv.zip to /content
  0% 0.00/33.1k [00:00<?, ?B/s]
100% 33.1k/33.1k [00:00<00:00, 122MB/s]

In [ ]:
!unzip titaniccsv.zip #Unzip the file

Archive:  titaniccsv.zip
  inflating: test.csv
  inflating: titanic.csv

In [ ]:
import pandas as pd

df = pd.read_csv("titanic.csv")
df.head(10000)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [ ]:
ls

kaggle.json  sample_data/  test.csv  titanic.csv  titaniccsv.zip

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    int64
 2   Pclass       891 non-null    int64
 3   Name         891 non-null    object
 4   Sex          891 non-null    object
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64
 7   Parch        891 non-null    int64
 8   Ticket       891 non-null    object
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object
 11  Embarked     889 non-null    object
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB

# ***`Column Selection and Filtering`***
``Select columns of interest``

In [ ]:
#Column selection means take a specific column name

df["Age"] #It show only column for multi columns df[["Age", "Sex"]]

0      22.0
1      38.0
2      26.0
3      35.0
4      35.0
       ...
886    27.0
887    19.0
888     NaN
889    26.0
890    32.0
Name: Age, Length: 891, dtype: float64

In [ ]:
#Filtering means select the data use condition .

df[df["Age"] > 30] # Means Upper 30 age

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
6,7,0,1,"McCarthy, Mr. Timothy J",male,54.0,0,0,17463,51.8625,E46,S
11,12,1,1,"Bonnell, Miss. Elizabeth",female,58.0,0,0,113783,26.5500,C103,S
...,...,...,...,...,...,...,...,...,...,...,...,...
873,874,0,3,"Vander Cruyssen, Mr. Victor",male,47.0,0,0,345765,9.0000,NaN,S
879,880,1,1,"Potter, Mrs. Thomas Jr (Lily Alexenia Wilson)",female,56.0,0,1,11767,83.1583,C50,C
881,882,0,3,"Markun, Mr. Johann",male,33.0,0,0,349257,7.8958,NaN,S
885,886,0,3,"Rice, Mrs. William (Margaret Norton)",female,39.0,0,5,382652,29.1250,NaN,Q
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q

***Another Example:-***

In [ ]:
df[df["Sex"] == "female"] # All female passenger , Only chose Female passenger .

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
8,9,1,3,"Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)",female,27.0,0,2,347742,11.1333,NaN,S
9,10,1,2,"Nasser, Mrs. Nicholas (Adele Achem)",female,14.0,1,0,237736,30.0708,NaN,C
...,...,...,...,...,...,...,...,...,...,...,...,...
880,881,1,2,"Shelley, Mrs. William (Imanita Parrish Hall)",female,25.0,0,1,230433,26.0000,NaN,S
882,883,0,3,"Dahlberg, Miss. Gerda Ulrika",female,22.0,0,0,7552,10.5167,NaN,S
885,886,0,3,"Rice, Mrs. William (Margaret Norton)",female,39.0,0,5,382652,29.1250,NaN,Q
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S

***`Multiple Condition Filtering`***

In [ ]:
#AND condition
df[(df["Age"] > 30) & (df["Sex"] == "female")] # Age > 30 AND female

#OR condition
df[(df["Age"] > 30) | (df["Sex"] == "female")] # Age > 30 OR female, in short female name upper 30 age .

#Column + Filter togather
df[df["Age"] > 30][["Name","Age"]] # Age > 30 , Only Name and column

                                                  Name   Age
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  38.0
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  35.0
4                             Allen, Mr. William Henry  35.0
6                              McCarthy, Mr. Timothy J  54.0
11                            Bonnell, Miss. Elizabeth  58.0
..                                                 ...   ...
873                        Vander Cruyssen, Mr. Victor  47.0
879      Potter, Mrs. Thomas Jr (Lily Alexenia Wilson)  56.0
881                                 Markun, Mr. Johann  33.0
885               Rice, Mrs. William (Margaret Norton)  39.0
890                                Dooley, Mr. Patrick  32.0

[305 rows x 2 columns]

``How many missing value in dataset checking this dataset.``

In [ ]:
print("\nMissing vaues in each column:")
df.isnull().sum() #This coding usage for which value missing (NaN) or not ? and sum count missing value , because total missing value number count.

##OutPut meaning :-

    #0 means no NaN missing value in column. if any number showing next to column that means , these number of missing values are NaN number in this column.

Missing vaues in each column:

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age            177
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
dtype: int64

# ***`Fill missing Base_encounter_cost values with the median`***

In [ ]:
df['Age'].fillna(df['Age'].median(), inplace=True) #df['Age'] means select the age column from dataset. here NaN means missing value, Calculate the median from Age column means middle value .fillna means replace missing value and fill median.
#Why median ?
#Because median is best and better than mean , If any outlier are present in dataset then mean creat so many problem.

# ***`Drop rows where 'ReasonDescription is missing'`***

In [ ]:
df.dropna(subset=['Embarked'], inplace=True)
print("\n After handling missing values")
df.head()

 After handling missing values

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
6,7,0,1,"McCarthy, Mr. Timothy J",male,54.0,0,0,17463,51.8625,E46,S
10,11,1,3,"Sandstrom, Miss. Marguerite Rut",female,4.0,1,1,PP 9549,16.7000,G6,S
11,12,1,1,"Bonnell, Miss. Elizabeth",female,58.0,0,0,113783,26.5500,C103,S

In [ ]:
df.isnull(

).sum()

PassengerId    0
Survived       0
Pclass         0
Name           0
Sex            0
Age            0
SibSp          0
Parch          0
Ticket         0
Fare           0
Cabin          0
Embarked       2
dtype: int64

# ***`What is Aggregation ?`***

     ``Aggregation means: So many data onvert into a summary value``

     e.g.,
          
          | Dept | Salary |
          | ---- | ------ |
          | IT   | 50000  |
          | IT   | 60000  |
          | HR   | 40000  |
          | HR   | 45000  |
      
      Here if we calculate average salary through Dept this is aggregation .

      What is GroupBy ?
          
          Group by means , Data group by columns .

          e.g,

          IT group → 50000, 60000
          HR group → 40000, 45000

          Mean means average

In [ ]:
df.groupby("Sex")["Age"].mean() #Average between Sex and Age

Sex
female    32.331579
male      37.279626
Name: Age, dtype: float64